### ISSUE TITLE
RefinedLibrarySupport - Inherited Facets

### ISSUE THREAD

**Issue by stevevickers** [commercetools/scraml#20]
When an inherited property has [facet definitions](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#scalar-types) which differ from the original definition, `RefinedLibrarySupport` generates invalid property declarations.

For example, an inherited property such as:

```
#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/base-without-facets-type"
displayName: BaseWithoutFacetsType
type: object
discriminator: type
properties:
  type: string
  id:
    type: string
```

Will define a property `id: String`.  If a derived type adds one or more facets to `id`, such as:

```
#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/child-with-facets-type"
displayName: ChildWithFacetsType
type: BaseWithoutFacetsType
discriminatorValue: child
properties:
  id:
    type: string
    pattern: ^[A-z]+$
```

The generated Scala code will not compile.

---

For this ticket to be successfully completed, logic in `RefinedLibrarySupport` must be enhanced such that:

* A warning is emitted when facets for any given property are not identical in a type's inheritance tree.
* Use the original property declaration in derived type(s).
* Use the union of discrete facet definitions, selected by a "first to be defined" policy, when generating companion `object` definitions.
