### ISSUE TITLE
Add support for RAML default facet

### ISSUE THREAD

**Issue by stevevickers** [commercetools/scraml#30]
Currently, when a type has the [default](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#type-declarations) facet specified, scraml does not incorporate it into the generated Scala code.  Support for `default` is orthogonal to `required` and therefore the generated properties will have Scala default values even if the property is required.

For example, a type such as:

```
#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/default-support"
displayName: TypeWithDefaultId
type: object
properties:
  id:
    type: string
    default: "the default id"
```

Should generate a Scala class functionally equivalent to:

```
final case class TypeWithDefaultId(id: String = "the default id")
```

The actual code generated can be different from the above, depending on what `LibrarySupport` and `FieldMatchPolicy` are enabled.
