### ISSUE TITLE
Add support for derived type properties being more specific

### ISSUE THREAD

**Issue by stevevickers** [commercetools/scraml#40]
According to the RAML specification for [Object Type Specialization](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#object-type-specialization):

> A sub-type MAY override properties of its parent type with the following restrictions: 1) a required property in the parent type cannot be changed to optional in the sub-type, and 2) the type declaration of a defined property in the parent type can only be changed to a narrower type (a specialization of the parent type) in the sub-type.

Currently, `scraml` does _not_ support a parent type property being marked `required: false` and a derived type having the same property marked as `required: true`, although according to the relevant specification quoted above, this is allowed.  For example:

```
#%RAML 1.0 DataType
(package): Example
(docs-uri): "https://example.org/parent-type"
displayName: Parent
type: object
properties:
  id?:
    type: string
```

```
#%RAML 1.0 DataType
(package): Example
(docs-uri): "https://example.org/derived-type"
displayName: Derived
type: Parent
properties:
  id:
    type: string
```

This will cause `scraml` to generate a `Parent` trait with a property definition of `def id: Option[String]` and a `Derived` case class with a constructor argument declared as `id: String`.  Since `Derived` extends `Parent` in this example, the code will not compile.
